In [1]:
import numpy as np
a= np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([1,2,3])#.reshape(3,1)
a * b + b


array([[ 2,  6, 12],
       [ 2,  6, 12],
       [ 2,  6, 12]])

In [4]:
a.shape

(3, 3)

In [2]:
np.cos(90.0)


-0.4480736161291702

In [2]:
def perp( a ) :
    b = np.empty_like(a)
    b[0] = -a[1]
    b[1] = a[0]
    return b

# line segment a given by endpoints a1, a2
# line segment b given by endpoints b1, b2
def seg_intersect(a1,a2, b1,b2) :
    """_summary_

    Args:
        a1 (np array of floats): Coordinates of one end of Line segment a
        a2 (np array of floats): Coordinates of other end of Line segment a
        b1 (np array of floats): Coordinates of one end of Line segment b
        b2 (np array of floats): Coordinates of other end of Line segment a

    Returns:
        np array of floats: Coordinates of point of intersection of Line segment a and b
    """
    da = a2-a1
    db = b2-b1
    dp = a1-b1
    dap = perp(da)
    denom = np.dot( dap, db)
    num = np.dot( dap, dp )
    return (num / denom) * db + b1

In [6]:
line_1 = np.array([(0,0),(0,5)])
line_2 = np.array([(1,0),(1,5)])
a= seg_intersect(line_1[0],line_1[1],line_2[0],line_2[1])
a

/var/folders/10/pb3d8l9j0k574h4mx201hv3m0000gn/T/ipykernel_12850/1987528859.py:27: RuntimeWarning: divide by zero encountered in scalar divide
  return (num / denom) * db + b1
/var/folders/10/pb3d8l9j0k574h4mx201hv3m0000gn/T/ipykernel_12850/1987528859.py:27: RuntimeWarning: invalid value encountered in multiply
  return (num / denom) * db + b1


array([nan, inf])

In [10]:
all(np.isfinite(a))

False

In [12]:
line_1 = np.array([(0,0),(0,5)])
line_2 = np.array([(1,0),(-1,5)])
a= seg_intersect(line_1[0],line_1[1],line_2[0],line_2[1])
a

array([0. , 2.5])

In [13]:
all(np.isfinite(a))

True